apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "vnmpocaks44"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "vnmpocaks44"
    spec:
      containers:
        - name: "vnmpocaks44"
          image: "vnmacr.azurecr.io/vnmpocaks44"
          ports:
          - containerPort: 8123