apiVersion : apps/v1
kind: Deployment
metadata:
  name: "vnmaks-9612"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "vnmaks-9612"
  template:
    metadata:
      labels:
        app: "vnmaks-9612"
    spec:
      containers:
        - name: "vnmaks-9612"
          image: "vnmacr.azurecr.io/vnmaksb6f1"
          ports:
          - containerPort: 8123