apiVersion: v1
kind: Service
metadata:
    name: "vnmpocaks44"
    labels:
        app: "vnmpocaks44"
spec:
    type: LoadBalancer
    ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "vnmpocaks44"