apiVersion: v1
kind: Service
metadata:
    name: "vnmpoc46"
    labels:
        app: "vnmpoc46"
spec:
    type: LoadBalancer
    ports:
    - port: 8123
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "vnmpoc46"