apiVersion: v1
kind: Service
metadata:
    name: "vnmaks-d162"
    labels:
        app: "vnmaks-d162"
spec:
    type: LoadBalancer
    ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    selector:
        app: "vnmaks-d162"