apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: vnmaks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: vnmaks
    spec:
      containers:
        - name: vnmaks
          image: vnmacr.azurecr.io/vnmaks
          ports:
          - containerPort: 80