apiVersion: v1
kind: Service
metadata:
    name: vnmaks
    labels:
        app: vnmaks
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: vnmaks