on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vnmacr.azurecr.io
        username: ${{secrets.acr_vnmacr_username}}
        password: ${{secrets.acr_vnmacr_password}}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/./" -f  "./aspnet-core-dotnet-core/Dockerfile" -t vnmacr.azurecr.io/vnmaksb6f1:${{github.sha}}
        docker push vnmacr.azurecr.io/vnmaksb6f1:${{github.sha}}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{secrets.aks_vnmaks_kubeConfig}}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vnmaksacaf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vnmaksacaf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vnmaksacaf
        container-registry-url: vnmacr.azurecr.io
        container-registry-username: ${{secrets.acr_vnmacr_username}}
        container-registry-password: ${{secrets.acr_vnmacr_password}}
        secret-name: vnmaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vnmaksacaf
        manifests: |
          manifests/deployment-8caf.yml
          manifests/service-8caf.yml
        images: |
          vnmacr.azurecr.io/vnmaksb6f1:${{github.sha}}
        imagepullsecrets: |
          vnmaksdockerauth