on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: vnmacr.azurecr.io
        username: ${{ secrets.acr_vnmacr_username }}
        password: ${{ secrets.acr_vnmacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t vnmacr.azurecr.io/vnmaks:${{ github.sha }}
        docker push vnmacr.azurecr.io/vnmaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vnmaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vnmaks9fad | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vnmaks9fad`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vnmaks9fad
        container-registry-url: vnmacr.azurecr.io
        container-registry-username: ${{ secrets.acr_vnmacr_username }}
        container-registry-password: ${{ secrets.acr_vnmacr_password }}
        secret-name: vnmaksdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: vnmaks9fad
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          vnmacr.azurecr.io/vnmaks:${{ github.sha }}
        imagepullsecrets: |
          vnmaksdockerauth