on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: aaaatiwarishubregistry.azurecr.io
        username: ${{ secrets.acr_aaaatiwarishubregistry_username }}
        password: ${{ secrets.acr_aaaatiwarishubregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/aspnet-core-dotnet-core" -f  "aspnet-core-dotnet-core/Dockerfile" -t aaaatiwarishubregistry.azurecr.io/vnmcontainerweb-img:${{ github.sha }}
        docker push aaaatiwarishubregistry.azurecr.io/vnmcontainerweb-img:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: vnm-container-web
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "aaaatiwarishubregistry.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.acr_aaaatiwarishubregistry_username }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.acr_aaaatiwarishubregistry_password }}",
              "slotSetting": false
            }            
          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: vnm-container-web
        images: aaaatiwarishubregistry.azurecr.io/vnmcontainerweb-img:${{ github.sha }}